version: "3.7"
services: 
    # Contenedor A
    mongo:
        container_name: mongo_db
        image: mongo:4.2
        ports:
            - 27018:27017
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: foo
            MONGO_INITDB_ROOT_PASSWORD: bar123
            MONGO_INITDB_DATABASE: Libreria
        volumes: 
            - volumen_mongo:/usr/src/Ordinario

    # Contenedor B
    mongo-express:
        container_name: dbms
        image: mongo-express
        restart: always
        ports:
            - 8082:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo_db
            ME_CONFIG_MONGODB_ADMINUSERNAME: foo
            ME_CONFIG_MONGODB_ADMINPASSWORD: bar123
            ME_CONFIG_BASICAUTH_USERNAME: foo
            ME_CONFIG_BASICAUTH_PASSWORD: bar123
            
    #Contenedor C
    pyhton:
        container_name: scraperLibros
        build: ./scrapper
        restart: on-failure:15
        ports: 
            - 5000:5000
        depends_on: 
            - mongo
        volumes: 
            - volumen_mongo:/usr/src/Ordinario
        env_file: 
            - ./scrapper/env.list

    # Contenedor D
    flask:
        container_name: pyapp
        build: ./flask
        restart: unless-stopped
        ports:
          - "5001:5000"
        volumes:
          - type: bind
            source: ./flask
            target: /usr/src/flask
        depends_on:
          - mongo
        env_file:
          - ./flask/env.list
          
    # Contenedor F
    vue:
        container_name: vue
        build: ./vue
        restart: on-failure:15
        volumes:
        - .:/vue
        ports:
        - 8079:8080
        depends_on: 
        - mongo
        - pyhton  
volumes: 
    volumen_mongo:
    